//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeRiskWeb.UserControls
{
    public partial class CaptchaControl
    {
        protected global::System.Web.UI.WebControls.Label lblPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtAnswer;
        protected global::System.Web.UI.WebControls.Button btnRefreshCaptcha;
    }
}