//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1_Assignment5
{
    public partial class AccountManagement
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// UsernameLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label UsernameLabel;

        /// <summary>
        /// RoleLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label RoleLabel;

        /// <summary>
        /// EmailBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EmailBox;

        /// <summary>
        /// SaveEmailBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button SaveEmailBtn;

        /// <summary>
        /// OldPasswordBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox OldPasswordBox;

        /// <summary>
        /// NewPasswordBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox NewPasswordBox;

        /// <summary>
        /// ConfirmPasswordBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox ConfirmPasswordBox;

        /// <summary>
        /// SavePasswordBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button SavePasswordBtn;

        /// <summary>
        /// MessageLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>
        /// BackBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BackBtn;
    }
}